### ISSUE TITLE
Current interceptor chains are not compatible with Axios interceptors

### ISSUE THREAD

**Issue by mgoodfellow** [suhaotian/xior#15]
See: https://github.com/axios/axios?tab=readme-ov-file#multiple-interceptors

Currently with xior - if the response interceptor throws, the chain ends: https://github.com/suhaotian/xior/blob/main/src/xior.ts#L239

I think it would be ideal to follow the same logic that axios uses to aid with drop-in replacements. In the case of the xior-auth-refresh plugin, I've noticed that any subsequent response error interceptors won't run.

**Comment by suhaotian** [comment]
I see, will fix in next version Thanks feedback!!   🙌

**Comment by suhaotian** [comment]
Merged then the issue automatic closed! (well done, github!)

**Comment by mgoodfellow** [comment]
Great thanks so much for this!

**Comment by mgoodfellow** [comment]
Fully validated, so pushed an updated version of the auth plugin which makes sure this version is used so avoid any unexpected behaviour!

Once again, thanks so much for the incredible turnaround - this library has been a lifesaver!

**Comment by suhaotian** [comment]
Cool, Thanks! @mgoodfellow 🙌
