### ISSUE TITLE
Named export xior cause problems in VS Code

### ISSUE THREAD

**Issue by guoyunhe** [suhaotian/xior#18]
When you type axios, VS Code auto-import like this:

```js
import axios from 'axios';

axios.post()
```

However, when you type xior, VS code auto-import like this:

```js
import { xior } from 'xior';

axios.post()
```

That is because xior has a named export called xior, which has higher priority than the default export. And they are different things?

```js
import xior from 'xior'; // instance
import { xior } from 'xior'; // class
```

In my opinion, class should always be CapitalCase. It should be:

```js
import xior from 'xior'; // instance
import { Xior } from 'xior'; // class
```

**Comment by suhaotian** [comment]
@guoyunhe 

Your feedback make sense! 

Fixed in v0.5.0! 

Thanks! 🙌
