### ISSUE TITLE
transformRequest method is missing

### ISSUE THREAD

**Issue by JustDenP** [suhaotian/xior#21]
Hello!
First of all, thank you for the perfect fetch library, but the only thing missing for me is transformRequest method from Axios to modify per-request options.

For example, if I need to completely remove some headers from specific requests, like Content-Type.
In axios we can do it like so:
```typescript
axiosInstance.post('/endpoint', { ... }, {
  transformRequest: [
    (data, headers) => {
      delete headers.common['Content-Type'];
      return JSON.stringify(data);
    },
  ],
});
```

Instead of creating separate clients or modifying defaults.
https://stackoverflow.com/questions/46656474/axios-remove-headers-authorization-in-1-call-only

**Comment by suhaotian** [comment]
Hey, Thanks for open this issue!

You can override with empty value by setting request configs:

> because in xior, request config's priority higher than defaults config.

```ts
axiosInstance.post('/endpoint', { ... }, {
  headers: {
    'Content-Type': '',
    'Authorization': ''
  },
});
```

**Comment by suhaotian** [comment]
Hey for the case of https://stackoverflow.com/questions/46656474/axios-remove-headers-authorization-in-1-call-only

We can override the value if use the defaults config:

```ts
xiorInstance.post('/endpoint', {...}, {
  headers: {
     'Authorization': '',
  }
})
```

For your case, I'm curious why you want delete the `Content-Type` in headers?

Because the default behaviour in xior.js, it will automatic process the data`JSON.stringify(data)` and add `Content-Type: 'application/json'` in `POST` method:

```ts
axiosInstance.post('/endpoint', { ... }, {
  transformRequest: [
    (data, headers) => {
      delete headers.common['Content-Type'];
      return JSON.stringify(data);
    },
  ],
});
```

```ts
xiorInstance.post('/endpoint', { ... }); 
```

Same with fetch:

```ts
fetch('/endpoint', {
  method: 'post', body: JSON.stringify({...}), headers: {'Content-Type': 'application/json'} 
})
```


For the feature `transformRequest` or `transformResponse`, May will consider to support in next version. Thanks!

**Comment by JustDenP** [comment]
Thanks for your answer, but there are cases when you want to remove the whole header, for example this one:
https://stackoverflow.com/questions/3508338/what-is-the-boundary-in-multipart-form-data

I use Xior also as a wrapper for Orval SDK generator, which sets some options, and headers automatically by provided openspec and with Content-Type multipart/form-data, I'm getting errors about missing Boundary. The only way I found to fix it - simply remove the Content-Type header and now it works.

The problem is I disabled the 'Content-Type': 'application/json' from my base Xior instance and I cannot use my SDK function, because I cannot override it

**Comment by suhaotian** [comment]
Here `'Content-Type': 'application/json'` is no necessary:

```ts
export const ApiClient = xior.create({
	baseURL,
	headers: {
		'Content-Type': 'application/json'
	},
	credentials: 'include'
});
```

Can just be:

```ts
export const ApiClient = xior.create({
	baseURL,
	credentials: 'include'
});
```

And upload file:

```ts
const formData = FormData();
formData.append('file', fileObject);
formData.append('field1', 'val1');
formData.append('field2', 'val2');

xiorInstance.post('/upload', formData, {
  onUploadProgress(e) {
    console.log(`Upload progress: ${e.progress}%`);
  },
  // progressDuration: 10 * 1000
});
```
