### ISSUE TITLE
Encoding query parameters question

### ISSUE THREAD

**Issue by yhnavein** [suhaotian/xior#22]
I was wondering why arrays are encoded in a way that my backend server does not understood them and I stumbled upon code for handling the params:

https://github.com/suhaotian/xior/blob/3a235b8babd0e6ecdb9b3eaa68e14ef702bf862d/src/utils.ts#L23C11-L23C12

```
        if (typeof value === 'object') {
          // If the value is an object or array, recursively encode its contents
          const result = encodeParams(value, encodeURI, encodedKey);
          if (result !== '') encodedParams.push(result);
        } else if (Array.isArray(value)) { // This will never be triggered because arrays are objects and they are handled in previous `if` statement
          // If the value is an array, encode each element individually
          value.forEach((element, index) => {
            const arrayKey = `${encodedKey}[${index}]`;
            encodedParams.push(`${encodeURIFunc(arrayKey)}=${encodeURIFunc(element)}`);
          });
        } else { ... }
```
Shouldn't be `if (Array.isArray(value))` be placed before check for `if (typeof value === 'object')`? Or maybe this check can be removed altogether?

Either way it won't particularly help me with my case (ASPNET uses totally different approach at encoding arrays...), but I just found it and I was intrigued by it.

**Comment by suhaotian** [comment]
Thank you feedback!

There are four different array encoding ways:

<img width="602" alt="image" src="https://github.com/suhaotian/xior/assets/6512574/073576e1-3c56-4b6e-9f38-92b74bb1819f">

Currently xior's default encoding is `'a[0]=b&a[1]=c'`, I want to know ASP.NET accept which encoding style?

**Comment by yhnavein** [comment]
I didn't know about `qs` has `arrayFormat`! 
It looks like ASPNET expects `arrayFormat='repeat'` and I implemented it as a custom serializer for my needs (pretty much the same code as attached in the https://github.com/suhaotian/xior/issues/23)

**Comment by suhaotian** [comment]
Let's continue discuss in this issue https://github.com/suhaotian/xior/issues/23
