### ISSUE TITLE
Memory Leak and Performance Issue Due to Uncleared Interceptors in xior

### ISSUE THREAD

**Issue by PetarIvanov01** [suhaotian/xior#27]
### Problem 
Each time an interceptor is added via `xior.interceptors.request.use` and `xior.interceptors.response.use`, it is pushed to an array and remains there indefinitely. There is no automatic cleanup mechanism for these interceptors, leading to a potential memory leak and performance issue when making multiple requests that add interceptors dynamically.

Example code snippet:
```javascript
const apiClient = xior.create({
  baseURL: "https://api.restful-api.dev/objects?id=3&id=5&id=10",
});

document.getElementById("btn").addEventListener("click", async (e) => {
  await getData();
  console.log(xior); // Here you can see how many interceptors are inside of both REQI and RESI arrays.
});

async function getData() {
  xior.interceptors.request.use((config) => {
    return config;
  });
  xior.interceptors.response.use((res) => {
    return res;
  });
  const data = await xior.get("/");
  return data;
}
```

Interceptors accumulate in the interceptor arrays (`REQI` and `RESI`) and are not cleaned up, leading to increased memory usage and potential performance impacts.

### Workaround Solution

I found that by manually ejecting the interceptors after their use within a request, the issue with interceptor accumulation can be temporarily resolved.  Here's the code snippet:

```javascript
const apiClient = xior.create({
  baseUrl: "https://api.restful-api.dev/objects?id=3&id=5&id=10",
});

document.getElementById("btn").addEventListener("click", async (e) => {
  await getData();
  console.log(xior);
});

async function getData() {
  // Adding interceptors
  const f1 = xior.interceptors.request.use((config) => {
    return config;
  });
  const f2 = xior.interceptors.response.use((res) => {
    return res;
  });

  // Performing the request
  const data = await xior.get("/");

  // Ejecting interceptors after their use
  xior.interceptors.request.eject(f1);
  xior.interceptors.response.eject(f2);

  return data;
}
```

### Proposed Solution
- **Automatic Cleanup:** Implement an automatic cleanup mechanism for interceptors that are no longer needed or used.
- **Improved Documentation:** Enhance documentation to guide users on proper management of interceptors, including the necessity and usage of the `eject` function to prevent memory leaks.

**Comment by suhaotian** [comment]
Hey, Thanks feedback!

The interceptors should be outside of functions:

```ts
const apiClient = xior.create({
  baseUrl: "https://api.restful-api.dev",
});

apiClient.interceptors.request.use((config) => {
    return config;
  });
apiClient.interceptors.response.use((res) => {
    return res;
  });

document.getElementById("btn").addEventListener("click", async (e) => {
  await getData();
  console.log(apiClient); // Here you can see how many interceptors are inside of both REQI and RESI arrays.
});

async function getData() {
  const data = await apiClient.get("/");
  return data;
}
```
