### ISSUE TITLE
Does not work on Vercel edge runtime 

### ISSUE THREAD

**Issue by peterarusanoff** [suhaotian/xior#3]
When i try to push I simply get 

```
    Error: The Edge Function "my/file/path" is referencing unsupported modules:
    - path/to/my/file.ts: xior
```

**Comment by suhaotian** [comment]
@peterarusanoff  

**Thanks report this issue!**

I add edge function in the `./next-example` and publish to vercel it's work:

Links:

https://xior-next-example.vercel.app/api/hello-edge (edge runtime)
https://xior-next-example.vercel.app/api/hello-node (nodejs runtime)

Example code here: 

https://github.com/suhaotian/xior/next-example/app/api/hello-edge/route.ts
https://github.com/suhaotian/xior/next-example/app/api/hello-node/route.ts

It would be nice, if you can paste your reproduce repo or code here.

**Comment by suhaotian** [comment]
I will close this, if still have problem, please feel free to reopen, and thanks for your feedback
