### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by fnoopv** [suhaotian/xior#6]
A [fetch()](https://developer.mozilla.org/en-US/docs/Web/API/fetch) promise will reject with a [TypeError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError) when a network error is encountered or CORS is misconfigured on the server-side, other situations are not. is this library the same?

**Comment by suhaotian** [comment]
Yes!
```ts
const http = xior.create({});

http.get('https://github.com').catch((e) => {
  console.log( e instanceof TypeError, e);
  throw e;
});
```
<img width="489" alt="image" src="https://github.com/suhaotian/xior/assets/6512574/8ee90e3d-e06c-423e-a675-c5b540ca17f6">

**Comment by fnoopv** [comment]
ok, thanks
