### ISSUE TITLE
Migrate axios to xior and why: use fetch, liteweight, similar axios API, plugins support

### ISSUE THREAD

**Issue by suhaotian** [suhaotian/xior#7]
# Migrate axios to xior

Guys, give [**xior**](https://www.npmjs.com/package/xior) a try, if have problems ,please feel free to create issue. 

According:

https://github.com/axios/axios/discussions/4477

https://github.com/axios/axios/issues/1219

https://github.com/axios/axios/issues/4965

https://github.com/axios/axios/issues/5145

https://github.com/axios/axios/issues/6008

https://github.com/axios/axios/issues/5523

https://github.com/vercel/next.js/issues/43120

https://github.com/openai/openai-node/issues/30

https://github.com/openai/openai-node/issues/30

https://github.com/slackapi/node-slack-sdk/issues/1335

https://github.com/contentful/contentful.js/issues/395

https://github.com/fzsirius/api_project/issues/3

https://github.com/cboard-org/cboard-ai-engine/issues/2

https://github.com/M4-Park-Checklist/m4-parks-frontend/issues/6

https://github.com/AlexandreBellas/bling-erp-api-js/issues/23

https://github.com/zerodevapp/sdk/issues/81

https://github.com/taraswww777/taraswww777.dev/issues/58

https://github.com/incyclist/desktop/issues/13

https://github.com/line/line-bot-sdk-nodejs/issues/531

https://github.com/axios/axios/issues/4793

**Comment by lil5** [comment]
@suhaotian why is this completed, I don't see it in the main branch?

**Comment by suhaotian** [comment]
@lil5 I didn't get it.. like the title, xior is based on fetch, similar API to axios, and support plugins.
